### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)"

### ISSUE THREAD

**Issue by Abutahir12** [aws/aws-dynamodb-encryption-python#748]
I am getting this issue in AWS Lambda when using the dynamodb encryption client, most online solutions suggests to downgrade the cryptography version, but this is being used internally, can anyone give me a possible solution for this problem?

**Comment by ramkumar-gopi** [comment]
I faced this similar issue. To fix this need to check the build OS GLIBC version `ldd --release` use this command to check it. If it doesnt match. Use Amazon linux 2 instance and try to run the build and deploy your lambda functions.

**Comment by ajewellamz** [comment]
Are you still having this problem?
If so, what OS version is your lambda using?
What pip command are you using to install?
What version of pyca/cryptography is your application using?

pyca/cryptography is the cryptographic primitive provider we use.
It binds to OpenSSL.
Your error may be caused by pyca/cryptography not being configured against the OpenSSL in your environment correctly.

https://github.com/pyca/cryptography

**Comment by texastony** [comment]
@Abutahir12 

We have not heard back from you about your compute environment.
I strongly suspect that @ramkumar-gopi and @ajewellamz are on the right track.
Recent releases of the `cryptography` dependency use Rust to call OpenSSL.

If you application is packaged in one environment,
but deployed/executes in another,
an incompatible binary would be created and this error would occur. 

Yes, downgrading `cryptography ` is a potential solution,
and that should work as this library depends on `cryptography>=3.4.6`,
which was before `cryptography` required Rust support.

But a better solution to your problem would be to
modify your application's packaging/building process
so that it targets the deployment environment,
not the build environment.

I am closing this issue.

@Abutahir12  if you have more questions, feel free to open a new issue.
