### ISSUE TITLE
Return plaintext values in ReturnValues field in response

### ISSUE THREAD

**Issue by thomasspatzier** [aws/aws-dynamodb-encryption-python#90]
I just found out that when I do a delete_item operation with ReturnValues='ALL_OLD', the entries in the Attributes dict of the response from dynamodb are not decrypted. Looking at the dynamodb encryption sdk code, it looks like delete_item is not handled.

It's a minor issue, but I was wondering if decryption support for 'ALL_OLD' attributes in delete_item responses is planned to be added.

**Comment by mattsb42-aws** [comment]
We don't have this planned at the moment, but I can see where this would be a useful feature.

We'll need to figure out what the right level of configuration will be, though. Having this on by default would not be the right answer because it would double the number of calls to your cryptographic materials provider, so this would be best surfaced as an opt-in behavior.

In the meantime, you can use the item encryptor functions[1] to decrypt the returned values similar to this example[2].

[1] https://aws-dynamodb-encryption-python.readthedocs.io/en/latest/lib/encrypted/item.html
[2] https://github.com/aws/aws-dynamodb-encryption-python/blob/master/examples/src/aws_kms_encrypted_item.py#L86

**Comment by thomasspatzier** [comment]
Thanks for the links. Using the item encryptor to do the decoding myself might actually be good enough. And, thinking about it, the app might have the already decrypted item it is trying to delete at hand anyway (that's why I thought it's a minor issue).
So I think I could live with item encryptor option. Thanks again for the suggestion and the quick response!

**Comment by mattsb42-aws** [comment]
In discussing with the team, we decided that this is something we want to do in order for the helper clients to properly behave as a drop-in replacement.

This will require a couple additional components:
* In order to avoid needing to hit the CMP twice for these calls, we will want to cache the plaintext key materials in an ephemeral CMP as described in #92.
* In order to be able to both actually decrypt the response and provide the caller with the expected output, we will need to provide a translation layer for the `UPDATED_OLD` and `UPDATED_NEW` options.

**Comment by mattsb42-aws** [comment]
Methods that accept the `ReturnValues` parameter are:
* `delete_item`
* `put_item`
* `update_item`

## update_item

We do not support `update_item`, so we can continue ignoring it. We should add a comment in the overloaded method, though, to remind us about this in case we ever do figure out a good way to support `update_item`.

## delete_item

`delete_item` only supports values `NONE` and `ALL_OLD`.

Because the only option that will return any part of an item includes the entire item, we do not need to worry about expanding or filtering results. We can just decrypt the item normally.

## put_item

In writing this up, I realized that we don't need to decrypt anything at all for the `*_NEW` options or do anything with ephemeral CMPs. We just need to hold onto the original plaintext item.

Possible options for `ReturnValues` are `NONE`, `ALL_OLD`, `UPDATED_OLD`, `ALL_NEW`, and `UPDATED_NEW`.

For `NONE`, nothing will be returned, so we can ignore it.

For `ALL_OLD` and `UPDATED_OLD`, we will need to use the CMP to decrypt the returned item.

We will also need to change `UPDATED_OLD` to `ALL_OLD` in order to decrypt the item, compare the results with the encrypted item that we sent to determine which attributes changed, then collect those attributes from the original plaintext item.

For `ALL_NEW` and `UPDATED_NEW`, we need to do the same as with `*_OLD` but we can skip the decryption step.

**Comment by mattsb42-aws** [comment]
Coming back to this:

This is going to necessarily introduce additional CMP `decryption_materials` calls when processing these return values for every case except for `put_item` `*_NEW`. We cannot assume that we will be able to reuse any materials, so will need to do an actual item decryption every time.

Because of this, we will need to leave this behavior disabled by default, with the ability to enable it when configuring the high-level clients.

As such, this will not require a minor-version bump because the return values will only change if the user specifically enables the feature.

**Comment by texastony** [comment]
I do not see us getting to this issue in a reasonable amount of time. 
The work around that Matt has provided will have to suffice. 
If this is an issue that is blocking other customers, please let us know by re-opening this or opening a new issue.
